'use client';
import {useEffect,useState,type ReactNode} from 'react';
import {Plus,Users,MapPin,Building2,Store,Layers,Save,X,ShieldCheck,Pencil,AlertCircle} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {NativeSelect} from '@/components/ui/native-select';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import type {AppUser,Location,LocationKind,WorkspaceContext} from '@/lib/access';
type UserForm={id:string;name:string;email:string;role:'admin'|'member';active:boolean;site_ids:string[]};
type LocationForm={id:string;kind:LocationKind;name:string;code:string;parent_id:string|null;active:boolean};
const hierarchy=[{kind:'area',label:'Areas',single:'area',Icon:MapPin},{kind:'project',label:'Projects',single:'project',Icon:Layers},{kind:'site',label:'Sites',single:'site',Icon:Building2},{kind:'store',label:'Stores',single:'store',Icon:Store}] as const;
const parentKind={project:'area',site:'project',store:'site'} as const;
function Field({label,children}:{label:string;children:ReactNode}){return <label className="field"><span>{label}</span>{children}</label>;}
export default function Administration({context,activeSite,onSaved}:{context:WorkspaceContext;activeSite:string;onSaved:()=>Promise<void>}){
 const [users,setUsers]=useState<AppUser[]>([]),[locations,setLocations]=useState<Location[]>([]),[tab,setTab]=useState('users'),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [user,setUser]=useState<UserForm|null>(null),[location,setLocation]=useState<LocationForm|null>(null),[legacySite,setLegacySite]=useState(activeSite),[storeSite,setStoreSite]=useState(activeSite);
 async function api(method='GET',body?:unknown){const r=await fetch('/api/admin',{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const d=await r.json() as {error?:string;locations:Location[];users:AppUser[]};if(!r.ok)throw Error(d.error||'Could not load administration.');return d;}
 async function load(){const d=await api();setUsers(d.users);setLocations(d.locations);setLoading(false);}
 useEffect(()=>{load().catch(e=>{setError(e.message);setLoading(false);});},[]);
 async function save(body:unknown,message:string){setBusy(true);setError('');try{await api('POST',body);await load();await onSaved();setUser(null);setLocation(null);setNotice(message);}catch(e){setError(e instanceof Error?e.message:'Could not save changes.');}finally{setBusy(false);}}
 function openLocation(kind:LocationKind){setError('');setLocation({id:crypto.randomUUID(),kind,name:'',code:'',parent_id:kind==='area'?null:kind==='store'?(storeSite||activeSite||null):null,active:true});}
 const editingLocation=!!location&&locations.some(l=>l.id===location.id),editingUser=!!user&&users.some(u=>u.id===user.id);
 const expectedParent=location&&location.kind!=='area'?parentKind[location.kind]:null;
 const parentOptions=expectedParent?locations.filter(l=>l.kind===expectedParent):[];
 return <div className="administration"><div className="page-heading"><div><div className="eyebrow">WORKSPACE ADMINISTRATION</div><h1>People and places.</h1><p>Manage your operating hierarchy and control access by site.</p></div><span className="badge"><ShieldCheck size={15}/>Administrator</span></div>
 <div className="hierarchy-strip">{hierarchy.map(({label,Icon,kind},n)=><div key={kind}><span className="hierarchy-step">{n+1}</span><Icon size={19}/><strong>{label}</strong><span>{locations.filter(l=>l.kind===kind).length}</span></div>)}</div>
 {error&&<div className="alert error" role="alert"><AlertCircle size={18}/><span>{error}</span><Button onClick={()=>load().catch(e=>setError(e.message))}>Retry</Button></div>}
 {notice&&<div className="alert success" role="status">{notice}</div>}
 {context.legacy_count>0&&<section className="panel legacy-panel"><h2>Assign existing records to a site</h2><p>{context.legacy_count} existing records are preserved in your previous workspace. Choose their destination site to make them available in the new hierarchy.</p><div className="actions"><Field label="Destination site"><NativeSelect value={legacySite} onChange={e=>setLegacySite(e.target.value)}><option value="">Choose an active site</option>{context.sites.map(s=><option key={s.id} value={s.id}>{s.name} ({s.code})</option>)}</NativeSelect></Field><Button disabled={!legacySite||busy} onClick={()=>save({action:'assign_legacy',site_id:legacySite},'Existing records assigned to the selected site.')}>Assign existing records</Button></div><p className="help">Recipe, menu, and ingredient references move together. Existing records in the destination are never overwritten.</p></section>}
 <Tabs value={tab} onValueChange={value=>{setTab(value);setError('');setNotice('');}}><TabsList className="admin-tabs"><TabsTrigger value="users"><Users size={17}/>Users <span>{users.length}</span></TabsTrigger>{hierarchy.map(({kind,label,Icon})=><TabsTrigger key={kind} value={kind}><Icon size={17}/>{label}</TabsTrigger>)}</TabsList>
 <TabsContent value="users"><div className="section-bar"><div><h2>User accounts</h2><p className="help">Administrators manage all sites. Site users can work only in their assigned sites.</p></div><Button className="primary" disabled={loading} onClick={()=>{setError('');setUser({id:crypto.randomUUID(),name:'',email:'',role:'member',active:true,site_ids:activeSite?[activeSite]:[]});}}><Plus size={17}/>Create user</Button></div><div className="inline-note">Users sign in with ChatGPT using the email entered here. Also grant them access through the app’s Share settings. Creating a profile does not send an invitation or change sharing.</div><section className="panel flush"><Table><TableHeader><TableRow><TableHead>Name / email</TableHead><TableHead>Role</TableHead><TableHead>Sites</TableHead><TableHead>Status</TableHead><TableHead></TableHead></TableRow></TableHeader><TableBody>{users.map(u=><TableRow key={u.id}><TableCell><strong>{u.name}</strong><small>{u.email}</small></TableCell><TableCell>{u.role==='admin'?'Administrator':'Site user'}{u.id==='workspace-owner'&&<small>Workspace owner</small>}</TableCell><TableCell>{u.role==='admin'?<span className="badge">All sites</span>:<div className="tags">{u.site_ids.map(id=><span className="badge" key={id}>{locations.find(l=>l.id===id)?.name||'Unavailable site'}</span>)}</div>}</TableCell><TableCell><span className={'badge '+(!u.active?'warn':'')}>{u.active?'Active':'Inactive'}</span><small>{u.auth_user_id?'Account linked':'Awaiting first sign-in'}</small></TableCell><TableCell><Button className="quiet" aria-label={'Edit user '+u.name} onClick={()=>{setError('');setUser({...u,active:!!u.active});}}><Pencil size={15}/>Edit</Button></TableCell></TableRow>)}</TableBody></Table>{loading&&<p className="padded">Loading users…</p>}</section></TabsContent>
 {hierarchy.map(({kind,label,single,Icon})=><TabsContent key={kind} value={kind}><div className="section-bar"><div><h2>{label}</h2><p className="help">{kind==='area'?'Areas group projects.':kind==='project'?'Every project belongs to an area.':kind==='site'?'Every site belongs to a project and keeps its operational data separate.':'Every store belongs to one site. Stores cannot be moved between sites.'}</p></div><div className="actions">{kind==='store'&&<NativeSelect aria-label="Filter stores by site" value={storeSite} onChange={e=>setStoreSite(e.target.value)}><option value="">All sites</option>{locations.filter(l=>l.kind==='site').map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</NativeSelect>}<Button className="primary" disabled={loading} onClick={()=>openLocation(kind)}><Plus size={17}/>Create {single}</Button></div></div><section className="panel flush"><Table><TableHeader><TableRow><TableHead>{single==='site'?'Site code / Food Pro ID':'Code'}</TableHead><TableHead>Name</TableHead>{kind!=='area'&&<TableHead>{parentKind[kind]}</TableHead>}<TableHead>Status</TableHead><TableHead></TableHead></TableRow></TableHeader><TableBody>{locations.filter(l=>l.kind===kind&&(kind!=='store'||!storeSite||l.parent_id===storeSite)).map(l=><TableRow key={l.id}><TableCell className="code">{l.code}</TableCell><TableCell><strong>{l.name}</strong></TableCell>{kind!=='area'&&<TableCell>{locations.find(p=>p.id===l.parent_id)?.name||'—'}</TableCell>}<TableCell><span className={'badge '+(!l.active?'warn':'')}>{l.active?'Active':'Inactive'}</span></TableCell><TableCell><Button className="quiet" aria-label={'Edit '+single+' '+l.name} onClick={()=>{setError('');setLocation({...l,active:!!l.active});}}><Pencil size={15}/>Edit</Button></TableCell></TableRow>)}</TableBody></Table>{!locations.some(l=>l.kind===kind&&(kind!=='store'||!storeSite||l.parent_id===storeSite))&&<div className="empty admin-empty"><Icon size={28}/><h3>No {label.toLowerCase()} yet</h3><p>{kind==='area'?'Create an area to begin the hierarchy.':`Create a ${single} and link it to its ${parentKind[kind]}.`}</p></div>}</section><p className="help">Deactivating a location prevents operational access to it and its descendants. Existing data is retained.</p></TabsContent>)}
 </Tabs>
 <Dialog open={!!location} onOpenChange={open=>{if(!open&&!busy)setLocation(null);}}>{location&&<DialogContent className="modal admin-modal" showCloseButton={false}><Button className="modal-close icon-button" aria-label="Close location editor" disabled={busy} onClick={()=>setLocation(null)}><X size={18}/></Button><DialogTitle>{editingLocation?'Edit':'Create'} {location.kind}</DialogTitle><DialogDescription>Link this location to the correct operating hierarchy.</DialogDescription><form onSubmit={e=>{e.preventDefault();void save({action:'location',record:location},`${location.name} saved.`);}}><div className="fields two"><Field label={location.kind==='site'?'Site code / Food Pro ID':'Unique '+location.kind+' code'}><Input required maxLength={100} value={location.code} onChange={e=>setLocation({...location,code:e.target.value})}/></Field><Field label="Name"><Input required maxLength={200} value={location.name} onChange={e=>setLocation({...location,name:e.target.value})}/></Field></div>{location.kind!=='area'&&<Field label={'Parent '+parentKind[location.kind]}><NativeSelect required disabled={editingLocation} value={location.parent_id||''} onChange={e=>setLocation({...location,parent_id:e.target.value||null})}><option value="">Choose {parentKind[location.kind]}</option>{parentOptions.map(p=><option key={p.id} value={p.id}>{p.name} ({p.code}){!p.active?' · inactive':''}</option>)}</NativeSelect></Field>}{location.kind==='site'&&<p className="help">Use the destination system’s site identifier. Recipe exports use this value in site_ids and this site’s name in site_names.</p>}{editingLocation&&location.kind!=='area'&&<p className="help">The parent is fixed to preserve site ownership and existing references.</p>}<label className="check"><Checkbox checked={location.active} onCheckedChange={v=>setLocation({...location,active:v===true})}/>Active {location.kind}</label>{error&&<p className="modal-error" role="alert">{error}</p>}<Button type="submit" className="primary full" disabled={busy}><Save size={17}/>{busy?'Saving…':'Save '+location.kind}</Button></form></DialogContent>}</Dialog>
 <Dialog open={!!user} onOpenChange={open=>{if(!open&&!busy)setUser(null);}}>{user&&<DialogContent className="modal admin-modal" showCloseButton={false}><Button className="modal-close icon-button" aria-label="Close user editor" disabled={busy} onClick={()=>setUser(null)}><X size={18}/></Button><DialogTitle>{editingUser?'Edit user':'Create user'}</DialogTitle><DialogDescription>Set the sign-in email, role, and permitted sites.</DialogDescription><form onSubmit={e=>{e.preventDefault();void save({action:'user',record:user},`${user.name} saved.`);}}><div className="fields two"><Field label="Full name"><Input required value={user.name} onChange={e=>setUser({...user,name:e.target.value})}/></Field><Field label="ChatGPT sign-in email"><Input required type="email" disabled={editingUser} value={user.email} onChange={e=>setUser({...user,email:e.target.value})}/></Field></div><Field label="Role"><NativeSelect disabled={user.id==='workspace-owner'||user.id===context.user.id} value={user.role} onChange={e=>setUser({...user,role:e.target.value as 'admin'|'member'})}><option value="member">Site user</option><option value="admin">Administrator · all sites</option></NativeSelect></Field>{user.role==='member'?<fieldset className="site-assignments"><legend>Assigned sites</legend>{locations.filter(l=>l.kind==='site').map(s=><label className="check" key={s.id}><Checkbox checked={user.site_ids.includes(s.id)} onCheckedChange={checked=>setUser({...user,site_ids:checked===true?[...user.site_ids,s.id]:user.site_ids.filter(id=>id!==s.id)})}/><span>{s.name}<small>{s.code}{s.active?'':' · inactive'}</small></span></label>)}{!locations.some(l=>l.kind==='site')&&<p>Create an area, project, and site before adding a site user.</p>}</fieldset>:<div className="inline-note">Administrators can manage all sites, locations, and user assignments.</div>}<label className="check"><Checkbox disabled={user.id==='workspace-owner'||user.id===context.user.id} checked={user.active} onCheckedChange={checked=>setUser({...user,active:checked===true})}/>Active user</label><p className="help">The first matching ChatGPT sign-in links this profile to that account. Site assignments are checked on every request.</p>{error&&<p className="modal-error" role="alert">{error}</p>}<Button type="submit" className="primary full" disabled={busy}><Save size={17}/>{busy?'Saving…':'Save user'}</Button></form></DialogContent>}</Dialog>
 </div>;
}
