'use client';
import {useEffect,useState,type ReactNode} from 'react';
import {Plus,Users,Layers,Save,X,Pencil,ShieldCheck} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {NativeSelect} from '@/components/ui/native-select';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {ROLE_LABELS,ROLE_DESCRIPTIONS,type Role} from '@/lib/permissions';
import type {AppUser,Project,WorkspaceContext} from '@/lib/access';
type UserForm={id:string;name:string;username:string;password:string;role:Role;active:boolean;project_id:string|null};
type ProjectForm={id:string;code:string;name:string;active:boolean;export_site_id:string;export_site_name:string};
function Field({label,children}:{label:string;children:ReactNode}){return <label className="field"><span>{label}</span>{children}</label>;}
export default function Administration({context,activeProject,onSaved}:{context:WorkspaceContext;activeProject:string;onSaved:()=>Promise<void>}){
 const [users,setUsers]=useState<AppUser[]>([]),[projects,setProjects]=useState<Project[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [user,setUser]=useState<UserForm|null>(null),[project,setProject]=useState<ProjectForm|null>(null),[legacyProject,setLegacyProject]=useState(activeProject),[legacyOwner,setLegacyOwner]=useState(context.legacy_groups[0]?.owner||'');
 async function api(method='GET',body?:unknown){const r=await fetch('/api/admin',{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const d=await r.json() as {error?:string;projects:Project[];users:AppUser[]};if(r.status===401||r.status===428){window.location.assign('/');throw Error('Please sign in again.');}if(!r.ok)throw Error(d.error||'Could not load administration.');return d;}
 async function load(){const d=await api();setUsers(d.users);setProjects(d.projects);setLoading(false);}
 useEffect(()=>{load().catch(e=>{setError(e.message);setLoading(false);});},[]);
 async function save(body:unknown,message:string){setBusy(true);setError('');try{await api('POST',body);await load();await onSaved();setUser(null);setProject(null);setNotice(message);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const editingProject=!!project&&projects.some(p=>p.id===project.id),editingUser=!!user&&users.some(u=>u.id===user.id);
 return <div className="administration"><div className="page-heading"><div><div className="eyebrow">ADMINISTRATION</div><h1>Projects and people.</h1><p>Organize kitchen work by project and assign your chefs.</p></div><span className="badge"><ShieldCheck size={15}/>Admin</span></div>
 {error&&<div className="alert error" role="alert">{error}<Button onClick={()=>load().catch(e=>setError(e.message))}>Retry</Button></div>}{notice&&<div className="alert success" role="status">{notice}</div>}
 {context.legacy_groups.length>0&&<section className="panel legacy-panel"><h2>Bring preserved records into a project</h2><p>Your previous records are retained. Move a complete workspace together to keep ingredient and menu references intact.</p><div className="fields two"><Field label="Preserved workspace"><NativeSelect value={legacyOwner} onChange={e=>setLegacyOwner(e.target.value)}><option value="">Choose workspace</option>{context.legacy_groups.map(g=><option key={g.owner} value={g.owner}>{g.name} ({g.count} records)</option>)}</NativeSelect></Field><Field label="Destination project"><NativeSelect value={legacyProject} onChange={e=>setLegacyProject(e.target.value)}><option value="">Choose project</option>{context.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</NativeSelect></Field></div><Button disabled={!legacyOwner||!legacyProject||busy} onClick={()=>save({action:'assign_legacy',owner:legacyOwner,project_id:legacyProject},'Preserved records moved into this project.')}>Move preserved records</Button><p className="help">Existing codes are never overwritten. If codes conflict, create a separate project for these records.</p></section>}
 <Tabs defaultValue="projects"><TabsList className="admin-tabs"><TabsTrigger value="projects"><Layers size={17}/>Projects <span>{projects.length}</span></TabsTrigger><TabsTrigger value="users"><Users size={17}/>Users <span>{users.length}</span></TabsTrigger></TabsList>
 <TabsContent value="projects"><div className="section-bar"><div><h2>Projects</h2><p className="help">Each project keeps its inventory, recipes, and menus separate.</p></div><Button className="primary" disabled={loading} onClick={()=>{setError('');setProject({id:crypto.randomUUID(),code:'',name:'',active:true,export_site_id:'',export_site_name:''});}}><Plus size={17}/>Create project</Button></div><section className="panel flush"><Table><TableHeader><TableRow><TableHead>Code</TableHead><TableHead>Project</TableHead><TableHead>Chefs</TableHead><TableHead>Status</TableHead><TableHead></TableHead></TableRow></TableHeader><TableBody>{projects.map(p=><TableRow key={p.id}><TableCell className="code">{p.code}</TableCell><TableCell><strong>{p.name}</strong></TableCell><TableCell>{users.filter(u=>u.role==='chef'&&u.project_id===p.id&&u.active).length}</TableCell><TableCell><span className="badge">{p.active?'Active':'Inactive'}</span></TableCell><TableCell><Button className="quiet" aria-label={'Edit project '+p.name} onClick={()=>{setError('');setProject({...p,active:!!p.active,export_site_id:p.export_site_id||'',export_site_name:p.export_site_name||''});}}><Pencil size={15}/>Edit</Button></TableCell></TableRow>)}</TableBody></Table>{!loading&&!projects.length&&<div className="empty"><Layers size={28}/><h3>Create your first project</h3><p>Then add chefs and assign them to it.</p></div>}</section><p className="help">Deactivating a project stops operational access and retains its records.</p></TabsContent>
 <TabsContent value="users"><div className="section-bar"><div><h2>User accounts</h2><p className="help">Admins manage all projects. Each chef works in one assigned project.</p></div><Button className="primary" disabled={loading} onClick={()=>{setError('');setUser({id:crypto.randomUUID(),name:'',username:'',password:'',role:'chef',active:true,project_id:activeProject||null});}}><Plus size={17}/>Create user</Button></div><section className="panel flush"><Table><TableHeader><TableRow><TableHead>Name / username</TableHead><TableHead>Role</TableHead><TableHead>Project</TableHead><TableHead>Status</TableHead><TableHead></TableHead></TableRow></TableHeader><TableBody>{users.map(u=><TableRow key={u.id}><TableCell><strong>{u.name}</strong><small>{u.username||'Login not configured'}</small></TableCell><TableCell>{ROLE_LABELS[u.role]}</TableCell><TableCell>{u.role==='admin'?'All projects':projects.find(p=>p.id===u.project_id)?.name||'Assign a project'}</TableCell><TableCell><span className="badge">{u.active?'Active':'Inactive'}</span><small>{!u.has_password?'Set a password':u.must_change?'Password change required':'Login ready'}</small></TableCell><TableCell><Button className="quiet" aria-label={'Edit user '+u.name} onClick={()=>{setError('');setUser({...u,username:u.username||'',password:'',active:!!u.active});}}><Pencil size={15}/>Edit</Button></TableCell></TableRow>)}</TableBody></Table></section><p className="help">Users sign in with a username and password. Share temporary passwords through your approved secure channel; users replace them on first sign-in.</p></TabsContent></Tabs>
 <Dialog open={!!project} onOpenChange={open=>{if(!open&&!busy)setProject(null);}}>{project&&<DialogContent className="modal admin-modal" showCloseButton={false}><Button className="modal-close icon-button" aria-label="Close project editor" disabled={busy} onClick={()=>setProject(null)}><X size={18}/></Button><DialogTitle>{editingProject?'Edit project':'Create project'}</DialogTitle><DialogDescription>Set up a separate workspace for this project.</DialogDescription><form onSubmit={e=>{e.preventDefault();void save({action:'project',record:project},`${project.name} saved.`);}}><div className="fields two"><Field label="Project code"><Input required maxLength={100} value={project.code} onChange={e=>setProject({...project,code:e.target.value})}/></Field><Field label="Project name"><Input required maxLength={200} value={project.name} onChange={e=>setProject({...project,name:e.target.value})}/></Field></div><details><summary>Food Pro export mapping (optional)</summary><p className="help">If Food Pro requires a specific scope, enter its real ID and name. Otherwise recipes export as shared using site_scope=all.</p><Field label="Food Pro scope ID"><Input value={project.export_site_id} onChange={e=>setProject({...project,export_site_id:e.target.value})}/></Field><Field label="Food Pro scope name"><Input value={project.export_site_name} onChange={e=>setProject({...project,export_site_name:e.target.value})}/></Field></details><label className="check"><Checkbox checked={project.active} onCheckedChange={v=>setProject({...project,active:v===true})}/>Active project</label>{error&&<p role="alert" className="modal-error">{error}</p>}<Button className="primary full" disabled={busy} type="submit"><Save size={17}/>{busy?'Saving…':'Save project'}</Button></form></DialogContent>}</Dialog>
 <Dialog open={!!user} onOpenChange={open=>{if(!open&&!busy)setUser(null);}}>{user&&<DialogContent className="modal admin-modal" showCloseButton={false}><Button className="modal-close icon-button" aria-label="Close user editor" disabled={busy} onClick={()=>setUser(null)}><X size={18}/></Button><DialogTitle>{editingUser?'Edit user':'Create user'}</DialogTitle><DialogDescription>Choose Admin or Chef. Assign each chef to one project.</DialogDescription><form onSubmit={e=>{e.preventDefault();void save({action:'user',record:user},`${user.name} saved.`);}}><div className="fields two"><Field label="Full name"><Input required maxLength={200} value={user.name} onChange={e=>setUser({...user,name:e.target.value})}/></Field><Field label="Username"><Input required autoComplete="off" minLength={3} maxLength={50} pattern="[A-Za-z0-9][A-Za-z0-9._-]*" value={user.username} onChange={e=>setUser({...user,username:e.target.value})}/></Field></div><Field label="Role"><NativeSelect disabled={user.id==='workspace-owner'||user.id===context.user.id} value={user.role} onChange={e=>setUser({...user,role:e.target.value as Role})}><option value="admin">Admin</option><option value="chef">Chef</option></NativeSelect></Field><p className="role-guide">{ROLE_DESCRIPTIONS[user.role]}</p>{user.role==='chef'&&<Field label="Assigned project"><NativeSelect required value={user.project_id||''} onChange={e=>setUser({...user,project_id:e.target.value||null})}><option value="">Choose a project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}{p.active?'':' · inactive'}</option>)}</NativeSelect></Field>}<Field label={editingUser?'Reset password (leave blank to keep current)':'Temporary password'}><Input type="password" autoComplete="new-password" required={!editingUser||!users.find(u=>u.id===user.id)?.has_password} minLength={7} maxLength={128} value={user.password} onChange={e=>setUser({...user,password:e.target.value})}/></Field><p className="help">Use 7–128 characters. Password resets require a password change at the next sign-in.</p><label className="check"><Checkbox disabled={user.id==='workspace-owner'||user.id===context.user.id} checked={user.active} onCheckedChange={v=>setUser({...user,active:v===true})}/>Active user</label><p className="help">Saving account changes signs this user out of existing sessions.</p>{error&&<p role="alert" className="modal-error">{error}</p>}<Button className="primary full" disabled={busy} type="submit"><Save size={17}/>{busy?'Saving…':'Save user'}</Button></form></DialogContent>}</Dialog>
 </div>;
}
