'use client';
import {useEffect,useState,type ReactNode} from 'react';
import {LockKeyhole} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
type Status={user?:{name:string;username:string;role:string}|null;must_change?:boolean;first_admin_available?:boolean};
export default function AuthGate({children}:{children:ReactNode}){
 const [status,setStatus]=useState<Status|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[current,setCurrent]=useState(''),[confirm,setConfirm]=useState(''),[change,setChange]=useState(false),[firstAdmin,setFirstAdmin]=useState(false),[name,setName]=useState('');
 async function load(){const r=await fetch('/api/auth');const d=await r.json() as Status & {error?:string};if(!r.ok)throw Error(d.error||'Sign-in is unavailable.');setStatus(d);setChange(new URLSearchParams(window.location.search).get('password')==='change');}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 const changing=!!status?.user&&(status.must_change||change),setup=firstAdmin&&!!status?.first_admin_available;
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if((changing||setup)&&password!==confirm){setError('The new passwords do not match.');return;}setBusy(true);try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:setup?'first_admin':changing?'change_password':'login',username,password,current_password:current,name})});const d=await r.json() as Status & {error?:string};if(!r.ok)throw Error(d.error||'Unable to sign in.');setPassword('');setCurrent('');setConfirm('');if(changing||setup)window.history.replaceState({},'','/');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(status?.user&&!changing)return children;
 return <div className="auth-page"><section className="auth-brand"><img className="auth-logo" src="/tafga-logo.png" alt="TAMIMI TAFGA"/><span>Recipe Studio</span><h1>Your kitchen.<br/>Your workspace.</h1><p>Recipes, inventory, and menus organized by project.</p></section><main className="auth-card"><LockKeyhole size={28}/><h2>{setup?'Create first Admin':changing?'Choose your password':'Sign in'}</h2><p>{setup?'Enter your name and choose your Admin username and password. This setup closes after the first Admin is created.':changing?(status?.must_change?'Replace your temporary password before opening the workspace.':'Update your password. Other sessions will be signed out.'):'Use the username and password provided by your administrator.'}</p>{!status&&!error?<p>Loading sign-in…</p>:<form onSubmit={submit}>{setup&&<><label className="field"><span>Full name</span><Input required maxLength={200} value={name} onChange={e=>setName(e.target.value)}/></label></>}{!changing&&<label className="field"><span>Username</span><Input required autoComplete="username" minLength={3} maxLength={50} value={username} onChange={e=>setUsername(e.target.value)}/></label>}{changing&&<label className="field"><span>Current or temporary password</span><Input required type="password" autoComplete="current-password" maxLength={128} value={current} onChange={e=>setCurrent(e.target.value)}/></label>}<label className="field"><span>{changing?'New password':'Password'}</span><Input required type="password" autoComplete={changing||setup?'new-password':'current-password'} minLength={changing||setup?7:undefined} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/></label>{(changing||setup)&&<><label className="field"><span>Confirm new password</span><Input required type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><p className="help">Use 7–128 characters. A long, unique passphrase works well.</p></>}{error&&<p className="modal-error" role="alert">{error}</p>}<Button className="primary full" type="submit" disabled={busy||!status}>{busy?'Please wait…':setup?'Create Admin':changing?'Save password':'Sign in'}</Button></form>}{!status&&error&&<Button onClick={()=>load().catch(e=>setError(e.message))}>Retry</Button>}{status&&!setup&&!changing&&<>{status.first_admin_available&&<Button className="full" onClick={()=>{setFirstAdmin(true);setError('');}}>Create first Admin</Button>}<p className="help">Forgot your password? Ask your administrator to set a temporary password.</p></>}{firstAdmin&&setup&&<Button onClick={()=>{setFirstAdmin(false);setError('');}}>Back to sign in</Button>}{changing&&!status?.must_change&&<a href="/">Cancel</a>}</main></div>;
}

