'use client';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {NativeSelect} from '@/components/ui/native-select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Dialog,DialogContent,DialogTitle} from '@/components/ui/dialog';
import {useEffect,useState,useRef,type ReactNode} from 'react';
import {ChefHat,BookOpen,PackageOpen,LayoutList,Download,Plus,Search,Trash2,Check,AlertCircle,FileSpreadsheet,Settings2,Utensils,ArrowLeft,Save,X,Copy,RefreshCw} from 'lucide-react';
import {ShieldCheck} from 'lucide-react';
import Administration from './administration';
import type {WorkspaceContext} from '@/lib/access';
import {UNITS,CATEGORIES,HEADERS,PATTERNS,blankRecipe,generateRecipe,inventoryCSV,csv,parseCSV,parseQuantity,mapIngredient,matchIngredients,recipeCost,lineCost,effectiveAllergens,recipesCSV,missingCSV,validateRecipe,round,type Recipe,type Inventory,type Menu} from '@/lib/food';
type Tab='Recipes'|'Inventory'|'Menus'|'Export center'|'Templates'|'Administration';
type Data={inventory:Inventory[];recipes:Recipe[];menus:Menu[]};
const money=(v:number|null)=>v===null?'Uncosted':v.toLocaleString('en',{minimumFractionDigits:2,maximumFractionDigits:2});
const list=(s:string)=>s.split(',').map(x=>x.trim());
function download(name:string,text:string){const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Field({label,children}: {label:string;children:ReactNode}){return <label className="field"><span>{label}</span>{children}</label>;}
function Empty({icon,title,children}:{icon:ReactNode;title:string;children:ReactNode}){return <div className="empty">{icon}<h3>{title}</h3>{children}</div>;}
function Badge({warn=false,children}:{warn?:boolean;children:ReactNode}){return <span className={'badge '+(warn?'warn':'')}>{children}</span>;}
const menuFields=['menu_code','menu_name','recipe_code','recipe_name','category','portions','selling_price','food_cost','food_cost_percent','contribution_margin'];
export default function Studio(){
 const [context,setContext]=useState<WorkspaceContext|null>(null),[activeSite,setActiveSite]=useState('');
 const activeSiteRef=useRef(''),loadSequence=useRef(0);
 const site=context?.sites.find(s=>s.id===activeSite);
 const scopeRecipe=(r:Recipe):Recipe=>site?{...r,site_scope:'specific',site_ids:[site.code],site_names:[site.name]}:r;
 const [tab,setTab]=useState<Tab>('Recipes'),[data,setData]=useState<Data>({inventory:[],recipes:[],menus:[]}),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState('');
 const [draft,setDraft]=useState<Recipe|null>(null),[dirty,setDirty]=useState(false),[generator,setGenerator]=useState(false),[pattern,setPattern]=useState(0),[batch,setBatch]=useState(10),[bulk,setBulk]=useState(''),[scale,setScale]=useState(10);
 const [pending,setPending]=useState<Inventory[]|null>(null),[item,setItem]=useState<Inventory|null>(null),[editItemCode,setEditItemCode]=useState('');
 const [menu,setMenu]=useState<Menu|null>(null),[menuDirty,setMenuDirty]=useState(false),[selected,setSelected]=useState<string[]|null>(null);
 const [menuCount,setMenuCount]=useState(4),[menuCategory,setMenuCategory]=useState('All categories');
 async function request(method='GET',body?:unknown,url='/api/data'){if(url.startsWith('/api/data')&&!/[?&]site=/.test(url))url+=(url.includes('?')?'&':'?')+'site='+encodeURIComponent(activeSiteRef.current);const r=await fetch(url,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});let d: Data & {error?:string};try{d=await r.json() as Data & {error?:string};}catch{throw Error('The service is unavailable. Your changes remain on screen.');}if(!r.ok)throw Error(d.error||'Request failed.');return d;}
 async function load(siteId=activeSiteRef.current){const seq=++loadSequence.current;if(!siteId){setData({inventory:[],recipes:[],menus:[]});setLoaded(false);return;}const d=await request('GET',undefined,'/api/data?site='+encodeURIComponent(siteId));if(seq===loadSequence.current&&activeSiteRef.current===siteId){setData(d);setLoaded(true);}}
 async function refreshContext(){const r=await fetch('/api/context');const c=await r.json() as WorkspaceContext & {error?:string};if(!r.ok)throw Error(c.error||'Could not load site access.');setContext(c);const next=c.sites.some(s=>s.id===activeSiteRef.current)?activeSiteRef.current:c.sites[0]?.id||'';activeSiteRef.current=next;setActiveSite(next);await load(next);}
 useEffect(()=>{refreshContext().catch(e=>setError(e.message));},[]);
 async function changeSite(id:string){if((dirty||menuDirty)&&!window.confirm('Change site and discard unsaved edits?'))return;activeSiteRef.current=id;setActiveSite(id);setData({inventory:[],recipes:[],menus:[]});setLoaded(false);setDraft(null);setMenu(null);setItem(null);setPending(null);setGenerator(false);setDirty(false);setMenuDirty(false);setSelected(null);setQuery('');setNotice('');await run(()=>load(id));}
 useEffect(()=>{const f=(e:BeforeUnloadEvent)=>{if(dirty||menuDirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f);},[dirty,menuDirty]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 function switchTab(t:Tab){if((dirty||menuDirty)&&!window.confirm('Leave this editor and discard unsaved changes?'))return;setTab(t);setDraft(null);setMenu(null);setDirty(false);setMenuDirty(false);setQuery('');setError('');setNotice('');}
 function edit(p:Partial<Recipe>){setDraft(d=>d?{...d,...p}:d);setDirty(true);}
 function editMenu(p:Partial<Menu>){setMenu(m=>m?{...m,...p}:m);setMenuDirty(true);}
 function openRecipe(r:Recipe){if(dirty&&!window.confirm('Discard the current unsaved recipe?'))return;setDraft(structuredClone(r));setScale(r.servings);setDirty(false);setError('');setBulk('');}
 async function saveRecipe(){if(!draft)return;const errs=validateRecipe(draft);if(errs.length){setError(errs.join(' '));return;}await run(async()=>{const r={...scopeRecipe(draft),ingredients:matchIngredients(draft.ingredients,data.inventory)};await request('POST',{kind:'recipe',record:r});setDraft(r);setDirty(false);await load();setNotice('Recipe saved.');});}
 async function remove(kind:string,id:string){if(!window.confirm('Delete this '+kind+'?'))return;await run(async()=>{await request('DELETE',undefined,`/api/data?kind=${kind}&id=${encodeURIComponent(id)}`);await load();setNotice('Deleted.');});}
 const filtered=data.recipes.filter(r=>(r.name+' '+r.recipe_code+' '+r.category).toLowerCase().includes(query.toLowerCase()));
 const chosen=data.recipes.filter(r=>selected===null||selected.includes(r.id));
 const missing=chosen.flatMap(r=>r.ingredients.filter(i=>!i.processing&&!mapIngredient(i,data.inventory)));
 const costs=draft?recipeCost(draft,data.inventory):null;
 const nav=[{name:'Recipes',icon:BookOpen},{name:'Inventory',icon:PackageOpen},{name:'Menus',icon:LayoutList},{name:'Export center',icon:Download},{name:'Templates',icon:Settings2},...(context?.user.role==='admin'?[{name:'Administration' as const,icon:ShieldCheck}]:[])] as const;
 function startMenu(){setMenu({id:crypto.randomUUID(),code:'MNU-'+crypto.randomUUID().slice(0,8).toUpperCase(),name:'New menu',target:30,items:[],columns:menuFields.map(s=>({header:s,field:s}))});setMenuDirty(true);}
 function addMenuRecipe(r:Recipe){if(!menu||menu.items.some(i=>i.recipe_id===r.id))return;const cost=recipeCost(r,data.inventory);editMenu({items:[...menu.items,{recipe_id:r.id,price:cost===null?0:Math.ceil(cost/(menu.target/100)),portions:1,sold:null}]});}
 const menuRecipes=menu?.items.map(i=>({item:i,recipe:data.recipes.find(r=>r.id===i.recipe_id)}))||[];
 const salesReady=menuRecipes.length>0&&menuRecipes.every(({item,recipe})=>item.sold!==null&&recipe&&recipeCost(recipe,data.inventory)!==null&&item.price>0)&&menuRecipes.reduce((n,x)=>n+(x.item.sold||0),0)>0;
 const totalSold=menuRecipes.reduce((n,x)=>n+(x.item.sold||0),0);
 const avgMargin=salesReady?menuRecipes.reduce((n,x)=>n+(x.item.price-recipeCost(x.recipe!,data.inventory)!)*(x.item.sold||0),0)/totalSold:0;
 function exportMenu(){if(!menu)return;try{const cols=menu.columns?.length?menu.columns:menuFields.map(s=>({header:s,field:s}));if(cols.some(c=>!c.header||!menuFields.includes(c.field)))throw Error('Map every menu template column before exporting.');const rows=menuRecipes.map(({item:i,recipe:r})=>{if(!r)throw Error('A menu recipe is missing.');const cost=recipeCost(r,data.inventory);const values:Record<string,unknown>={menu_code:menu.code,menu_name:menu.name,recipe_code:r.recipe_code,recipe_name:r.name,category:r.category,portions:i.portions,selling_price:i.price,food_cost:cost===null?'':round(cost),food_cost_percent:cost===null||!i.price?'':round(cost/i.price*100),contribution_margin:cost===null?'':round(i.price-cost)};return cols.map(c=>values[c.field]);});download('menu.csv',csv([cols.map(c=>c.header),...rows]));setNotice('Menu CSV downloaded using the selected column mapping.');}catch(e){setError((e as Error).message);}}
 return <div className="app"><aside className="sidebar"><div className="brand"><div className="brand-mark"><ChefHat size={24}/></div><div>Recipe Studio<small>FOOD PRO WORKSPACE</small></div></div><div className="nav-label">KITCHEN OPERATIONS</div><nav>{nav.map(({name,icon:Icon})=><Button key={name} className={tab===name?'nav active':'nav'} onClick={()=>switchTab(name)}><Icon size={19}/>{name}{name==='Recipes'&&<span>{data.recipes.length}</span>}</Button>)}</nav><div className="sidebar-bottom"><span className="mini-logo">FP</span><div>Production workspace<small>Inventory-linked recipes</small></div></div></aside>
 <div className="workspace"><header className="topbar"><span>Workspace <span className="slash">/</span> <strong>{tab}</strong></span><div className="site-toolbar">{context&&<label className="site-picker"><span>Working site</span><NativeSelect aria-label="Working site" disabled={busy} value={activeSite} onChange={e=>changeSite(e.target.value)}><option value="">Choose a site</option>{context.sites.map(s=><option value={s.id} key={s.id}>{s.name} ({s.code})</option>)}</NativeSelect></label>}<span className="top-note">{context?.user.name||'Private workspace'}</span></div></header><main>
 {error&&<div className="alert error" role="alert"><AlertCircle size={19}/><span>{error}</span><Button aria-label="Dismiss error" onClick={()=>setError('')}><X size={17}/></Button>{!loaded&&<Button onClick={()=>run(refreshContext)}>Retry</Button>}</div>}
 {notice&&<div className="alert success" role="status"><Check size={18}/><span>{notice}</span><Button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={17}/></Button></div>}
 {!context&&!error&&<div className="loading">Loading your site access…</div>}
 {context&&!activeSite&&tab!=='Administration'&&<div className="inline-note">{context.user.role==='admin'?'Create an area, project, and site in Administration, then select a working site.':'No active site is available. Ask an administrator to review your site assignments.'}{context.user.role==='admin'&&<Button onClick={()=>switchTab('Administration')}>Open administration</Button>}</div>}
 {context&&context.legacy_count>0&&tab!=='Administration'&&<div className="inline-note">Your existing records are preserved. Assign them to a site in Administration to continue using them.</div>}
 {tab==='Administration'&&context?.user.role==='admin'&&<Administration context={context} activeSite={activeSite} onSaved={refreshContext}/>}
 {tab==='Recipes'&&!draft&&<><div className="page-heading"><div><div className="eyebrow">RECIPE LIBRARY</div><h1>Your kitchen, documented.</h1><p>Create, cost, and prepare recipes for Food Pro.</p></div><Button className="primary" disabled={!loaded||busy} onClick={()=>setGenerator(true)}><Plus size={18}/>Create recipe</Button></div>
 <div className="start-strip"><div className="strip-icon"><Utensils size={25}/></div><div><h3>Start with a recipe. Make it yours.</h3><p>Generate an editable batch from a recipe pattern, then map it to your inventory.</p></div><Button onClick={()=>setGenerator(true)} disabled={!loaded}>Generate a recipe</Button></div>
 <div className="section-bar"><h2>All recipes <span className="count">{data.recipes.length}</span></h2><label className="search"><Search size={17}/><Input placeholder="Search name, code, or category" aria-label="Search recipes" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 {filtered.length?<div className="recipe-grid">{filtered.map(r=>{const cost=recipeCost(r,data.inventory),n=r.ingredients.filter(i=>!i.processing&&!mapIngredient(i,data.inventory)).length;return <article className="recipe-card" key={r.id}><div className="recipe-card-head"><span className="category-icon"><Utensils size={22}/></span><Badge warn={n>0}>{n?`${n} unmapped`:'Mapped'}</Badge></div><span className="overline">{r.cuisine_type==='philippines'?'FILIPINO':r.category.toUpperCase()}</span><h3><Button onClick={()=>openRecipe(r)}>{r.name}</Button></h3><p className="recipe-code">{r.recipe_code}</p><div className="recipe-facts"><span>{r.servings} servings</span><span>{r.prep_time_minutes+r.cook_time_minutes} min</span></div><div className="recipe-card-foot"><div><small>COST / PORTION</small><strong>{cost===null?'Uncosted':`SAR ${money(cost)}`}</strong></div><Button className="quiet" onClick={()=>openRecipe(r)}>Open recipe</Button><Button className="icon-button" aria-label={'Delete '+r.name} disabled={busy} onClick={()=>remove('recipe',r.id)}><Trash2 size={16}/></Button></div></article>;})}</div>:<Empty icon={<BookOpen size={32}/>} title={query?'No matching recipes':'Your recipe library starts here'}><p>{query?'Try a different search.':'Import your inventory, then generate a recipe or enter your own.'}</p><Button onClick={()=>switchTab('Inventory')}>Open inventory</Button><Button className="quiet" disabled={!loaded} onClick={()=>{setDraft(scopeRecipe(blankRecipe()));setDirty(true);}}>Create from scratch</Button></Empty>}
 <div className="workflow"><span><b>01</b> Import inventory</span><span><b>02</b> Create recipes</span><span><b>03</b> Build your menu</span><span><b>04</b> Export to Food Pro</span></div></>}
 {tab==='Recipes'&&draft&&<><Button className="back" onClick={()=>switchTab('Recipes')}><ArrowLeft size={16}/>Recipe library</Button><div className="page-heading"><div><div className="eyebrow">RECIPE BUILDER</div><h1>{draft.name||'New recipe'}</h1><p>{dirty?'Unsaved changes':'Saved recipe'} · Review quantities and yield before production.</p></div><div className="actions"><Button onClick={()=>{const r={...draft,id:crypto.randomUUID(),recipe_code:blankRecipe().recipe_code,name:draft.name+' (copy)'};setDraft(r);setDirty(true);}}><Copy size={17}/>Duplicate</Button><Button className="primary" disabled={busy} onClick={saveRecipe}><Save size={17}/>{busy?'Saving…':'Save recipe'}</Button></div></div>
 <div className="editor-layout"><div><section className="panel"><h2>Recipe details</h2><div className="fields two"><Field label="Recipe name"><Input value={draft.name} onChange={e=>edit({name:e.target.value})}/></Field><Field label="Unique recipe code"><Input value={draft.recipe_code} onChange={e=>edit({recipe_code:e.target.value})}/></Field><Field label="Cuisine"><NativeSelect value={draft.cuisine_type} onChange={e=>edit({cuisine_type:e.target.value})}><option value="general">General</option><option value="philippines">Philippines</option></NativeSelect></Field><Field label="Category"><NativeSelect value={draft.category} onChange={e=>edit({category:e.target.value})}>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</NativeSelect></Field><Field label="Batch servings"><Input type="number" min="1" value={draft.servings} onChange={e=>edit({servings:Number(e.target.value)})}/></Field><Field label="Portion size (grams)"><Input type="number" min="1" value={draft.portion_size_grams} onChange={e=>edit({portion_size_grams:Number(e.target.value)})}/></Field></div><p className="help">Changing batch servings changes the yield only. Use Scale batch to scale every ingredient.</p><Field label="Description"><textarea rows={2} value={draft.description} onChange={e=>edit({description:e.target.value})}/></Field></section>
 <section className="panel"><div className="section-bar"><h2>Ingredients <span className="count">{draft.ingredients.length}</span></h2><Button onClick={()=>edit({ingredients:matchIngredients(draft.ingredients,data.inventory)})}><RefreshCw size={15}/>Match exact names</Button></div>{!data.inventory.length&&<div className="inline-note">Import real inventory to map item codes. Unmatched ingredients will export with blank codes.</div>}
 <div className="ingredient-list">{draft.ingredients.map((i,index)=>{const m=mapIngredient(i,data.inventory);return <div className="ingredient" key={index}><div className="ingredient-top"><span className="ingredient-number">{String(index+1).padStart(2,'0')}</span><Input aria-label={'Ingredient '+(index+1)+' name'} placeholder="Ingredient name" value={i.name} onChange={e=>edit({ingredients:draft.ingredients.map((x,n)=>n===index?{...x,name:e.target.value,item_code:''}:x)})}/><Badge warn={!m&&!i.processing}>{i.processing?'Prep only':m?'Mapped':'Unmatched'}</Badge><Button className="icon-button" aria-label={'Remove ingredient '+(index+1)} onClick={()=>edit({ingredients:draft.ingredients.filter((_,n)=>n!==index)})}><X size={17}/></Button></div><div className="ingredient-inputs"><Field label="Quantity"><Input type="number" step="any" min="0" value={i.quantity} onChange={e=>edit({ingredients:draft.ingredients.map((x,n)=>n===index?{...x,quantity:Number(e.target.value),source:e.target.value+' '+x.unit,original_servings:draft.servings}:x)})}/></Field><Field label="Unit"><NativeSelect value={i.unit} onChange={e=>edit({ingredients:draft.ingredients.map((x,n)=>n===index?{...x,unit:e.target.value,source:x.quantity+' '+e.target.value,original_servings:draft.servings}:x)})}>{UNITS.map(u=><option key={u}>{u}</option>)}</NativeSelect></Field><Field label="Inventory item"><NativeSelect value={m?.item_code||''} onChange={e=>edit({ingredients:draft.ingredients.map((x,n)=>n===index?{...x,item_code:e.target.value}:x)})}><option value="">Unmatched</option>{data.inventory.map(x=><option key={x.item_code} value={x.item_code}>{x.item_code} — {x.name}</option>)}</NativeSelect></Field><span className="line-cost">{money(lineCost(i,data.inventory))}<small>SAR</small></span></div><div className="ingredient-meta"><span>Source: {i.source} / {i.original_servings} servings</span>{/water/i.test(i.name)&&<label className="check"><Input type="checkbox" checked={i.processing} onChange={e=>edit({ingredients:draft.ingredients.map((x,n)=>n===index?{...x,processing:e.target.checked}:x)})}/>Discarded prep water · exclude from export</label>}</div></div>;})}</div>
 <Button className="dashed" onClick={()=>edit({ingredients:[...draft.ingredients,{name:'',item_code:'',quantity:1,unit:'kg',source:'1 kg',original_servings:draft.servings,processing:false}]})}><Plus size={17}/>Add ingredient</Button><details><summary>Paste ingredient quantities</summary><textarea aria-label="Ingredient lines" placeholder={'2 kg Chicken breast\n45 kg to 50 kg Rice'} rows={3} value={bulk} onChange={e=>setBulk(e.target.value)}/><Button onClick={()=>{try{const lines=bulk.split('\n').filter(x=>x.trim()).map(s=>({...parseQuantity(s),item_code:'',source:s,original_servings:draft.servings,processing:false}));edit({ingredients:[...draft.ingredients,...matchIngredients(lines,data.inventory)]});setBulk('');setError('');}catch(e){setError((e as Error).message);}}}>Add lines</Button><p className="help">Ranges use the upper quantity and preserve the original text.</p></details></section>
 <section className="panel"><h2>Cooking method</h2><Field label="One step per line"><textarea rows={7} value={draft.instructions} onChange={e=>edit({instructions:e.target.value})}/></Field><div className="fields two"><Field label="Prep time (minutes)"><Input type="number" min="0" value={draft.prep_time_minutes} onChange={e=>edit({prep_time_minutes:Number(e.target.value)})}/></Field><Field label="Cook time (minutes)"><Input type="number" min="0" value={draft.cook_time_minutes} onChange={e=>edit({cook_time_minutes:Number(e.target.value)})}/></Field></div></section>
 <section className="panel"><h2>Food Pro fields</h2><div className="fields two"><Field label="Recipe type (destination value)"><Input value={draft.recipe_type} onChange={e=>edit({recipe_type:e.target.value})}/></Field><Field label="Site scope"><NativeSelect disabled value="specific" onChange={e=>edit({site_scope:e.target.value})}><option value="all">All sites</option><option value="specific">Specific sites</option></NativeSelect></Field>{true&&<><Field label="Site ID from current site"><Input readOnly value={site?.code||''}/></Field><Field label="Current site name"><Input readOnly value={site?.name||''}/></Field></>}<Field label="Known recipe allergens (comma separated)"><Input value={draft.allergens.join(',')} onChange={e=>edit({allergens:e.target.value?list(e.target.value):[]})}/></Field><Field label="Image URL (optional)"><Input type="url" value={draft.image_url} onChange={e=>edit({image_url:e.target.value})}/></Field></div><label className="check"><Input type="checkbox" checked={draft.is_active} onChange={e=>edit({is_active:e.target.checked})}/>Active recipe</label><p className="help">Recipes and exports belong to the working site. Mapped ingredient allergens are included automatically. Review supplier declarations. This version exports sub_recipes as [].</p></section></div>
 <aside className="recipe-summary"><section className="cost-panel"><span className="eyebrow">RECIPE COSTING</span><h2>{costs===null?'Uncosted':`SAR ${money(costs)}`}</h2><p>per portion</p><div><span>Batch cost</span><strong>{costs===null?'—':money(costs*draft.servings)}</strong></div><div><span>Batch yield</span><strong>{draft.servings} portions</strong></div><div><span>Portion size</span><strong>{draft.portion_size_grams} g</strong></div><small>Ingredient cost only. Packaging, labour, tax, and overhead are excluded.</small></section><section className="panel"><h3>Scale batch</h3><Field label="New serving count"><Input type="number" min="1" value={scale} onChange={e=>setScale(Number(e.target.value))}/></Field><Button className="full" disabled={!scale||scale<=0||draft.servings<=0} onClick={()=>edit({servings:scale,ingredients:draft.ingredients.map(i=>({...i,quantity:round(i.quantity*scale/draft.servings)}))})}>Scale all quantities</Button></section><section className="panel"><h3>Export readiness</h3><p>{draft.ingredients.filter(i=>!i.processing&&mapIngredient(i,data.inventory)).length} mapped ingredients</p><p>{draft.ingredients.filter(i=>!i.processing&&!mapIngredient(i,data.inventory)).length} need mapping</p><p className="help">Unknown prices or incompatible units prevent complete costing.</p><hr/><h3>Allergens</h3><div className="tags">{effectiveAllergens(draft,data.inventory).map(a=><Badge key={a}>{a}</Badge>)}</div>{!effectiveAllergens(draft,data.inventory).length&&<p className="help">None declared. Verify before production.</p>}</section></aside></div></>}
 {tab==='Inventory'&&<><div className="page-heading"><div><div className="eyebrow">INVENTORY MASTER</div><h1>The source of every ingredient.</h1><p>Exact item codes, units, costs, and allergen declarations.</p></div><Button className="primary" disabled={!loaded} onClick={()=>{setItem({id:'',item_code:'',name:'',unit:'kg',cost:null,category:'Ingredient',allergens:[]});setEditItemCode('');}}><Plus size={18}/>Add item</Button></div><section className="import-box"><FileSpreadsheet size={32}/><div><h3>Import your Food Pro inventory</h3><p>CSV columns: item_code, name, unit. Optional: cost, category, allergens.</p><p className="help">Cost is per listed system unit. Allergens use a JSON array. Existing codes are updated after review.</p></div><div className="actions"><Button onClick={()=>download('inventory-template.csv',csv([['item_code','name','unit','cost','category','allergens']]))}>Download template</Button><label className="button primary">Choose CSV<Input type="file" accept=".csv,text/csv" hidden disabled={busy||!loaded} onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{if(f.size>5000000)throw Error('Use a CSV smaller than 5 MB.');const items=inventoryCSV(await f.text());if(!items.length)throw Error('Add inventory rows beneath the headers.');if(items.length>5000)throw Error('Import up to 5,000 items at a time.');setPending(items);setError('');}catch(e){setError((e as Error).message);}}}/></label></div></section>
 {pending&&<section className="panel"><div className="section-bar"><h2>Review import</h2><Badge>{pending.length} items</Badge></div><p>{pending.filter(x=>data.inventory.some(y=>y.item_code===x.item_code)).length} existing item codes will be updated.</p><div className="table-wrap"><Table><TableHeader><TableRow><TableHead>Item code</TableHead><TableHead>Name</TableHead><TableHead>Unit</TableHead><TableHead>Cost / unit</TableHead></TableRow></TableHeader><TableBody>{pending.slice(0,8).map(i=><TableRow key={i.item_code}><TableCell className="code">{i.item_code}</TableCell><TableCell>{i.name}</TableCell><TableCell>{i.unit}</TableCell><TableCell>{money(i.cost)}</TableCell></TableRow>)}</TableBody></Table></div>{pending.length>8&&<p className="help">Showing the first 8 of {pending.length} items.</p>}<div className="actions"><Button className="primary" disabled={busy} onClick={()=>run(async()=>{let saved=0;try{for(let n=0;n<pending.length;n+=100){await request('POST',{kind:'inventory',items:pending.slice(n,n+100)});saved+=Math.min(100,pending.length-n);}}catch(e){await load();throw Error(`${saved} items imported before the error. Retrying safely updates those same codes. ${(e as Error).message}`);}await load();setPending(null);setNotice(`${saved} inventory items saved.`);})}>{busy?'Importing…':'Confirm import'}</Button><Button disabled={busy} onClick={()=>setPending(null)}>Cancel</Button></div></section>}
 <div className="section-bar"><h2>Inventory <span className="count">{data.inventory.length}</span></h2><label className="search"><Search size={17}/><Input aria-label="Search inventory" placeholder="Search item name or code" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>{data.inventory.length?<div className="table-wrap panel flush"><Table><TableHeader><TableRow><TableHead>Item code</TableHead><TableHead>Ingredient</TableHead><TableHead>Unit</TableHead><TableHead>Cost / unit (SAR)</TableHead><TableHead>Allergens</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{data.inventory.filter(i=>(i.name+' '+i.item_code).toLowerCase().includes(query.toLowerCase())).map(i=><TableRow key={i.item_code}><TableCell className="code">{i.item_code}</TableCell><TableCell><strong>{i.name}</strong><small>{i.category}</small></TableCell><TableCell>{i.unit}</TableCell><TableCell>{money(i.cost)}</TableCell><TableCell>{i.allergens.join(', ')||'Not declared'}</TableCell><TableCell><Button className="quiet" onClick={()=>{setItem(structuredClone(i));setEditItemCode(i.item_code);}}>Edit</Button><Button className="icon-button" aria-label={'Delete '+i.name} disabled={busy} onClick={()=>remove('inventory',i.id)}><Trash2 size={16}/></Button></TableCell></TableRow>)}</TableBody></Table></div>:<Empty icon={<PackageOpen size={34}/>} title="Bring your real inventory"><p>Import a CSV or add an item. No placeholder codes are created.</p></Empty>}</>}
 {tab==='Menus'&&!menu&&<><div className="page-heading"><div><div className="eyebrow">MENU ENGINEERING</div><h1>Recipes become a menu.</h1><p>Plan production, set prices, and compare contribution margins.</p></div><Button className="primary" disabled={!loaded||!data.recipes.length} onClick={startMenu}><Plus size={18}/>Create menu</Button></div>{!data.menus.length?<Empty icon={<LayoutList size={34}/>} title="Build from your recipe library"><p>Save recipes first, then generate a menu and adjust its prices.</p><Button onClick={()=>switchTab('Recipes')}>Open recipes</Button></Empty>:<div className="recipe-grid">{data.menus.map(m=><article className="recipe-card" key={m.id}><span className="overline">{m.code}</span><h3>{m.name}</h3><p>{m.items.length} recipes · {m.target}% target food cost</p><div className="actions"><Button onClick={()=>{setMenu(structuredClone(m));setMenuDirty(false);}}>Open menu</Button><Button className="icon-button" aria-label={'Delete '+m.name} disabled={busy} onClick={()=>remove('menu',m.id)}><Trash2 size={17}/></Button></div></article>)}</div>}</>}
 {tab==='Menus'&&menu&&<><Button className="back" onClick={()=>switchTab('Menus')}><ArrowLeft size={16}/>Menus</Button><div className="page-heading"><div><div className="eyebrow">MENU BUILDER</div><h1>{menu.name}</h1><p>{menuDirty?'Unsaved changes':'Saved menu'} · Prices exclude tax.</p></div><div className="actions"><Button disabled={!menu.items.length} onClick={exportMenu}><Download size={17}/>Menu CSV</Button><Button className="primary" disabled={busy||!menu.items.length} onClick={()=>run(async()=>{await request('POST',{kind:'menu',record:menu});setMenuDirty(false);await load();setNotice('Menu saved.');})}><Save size={17}/>Save menu</Button></div></div><section className="panel"><div className="fields three"><Field label="Menu name"><Input value={menu.name} onChange={e=>editMenu({name:e.target.value})}/></Field><Field label="Unique menu code"><Input value={menu.code} onChange={e=>editMenu({code:e.target.value})}/></Field><Field label="Target food cost (%)"><Input type="number" min="1" max="100" value={menu.target} onChange={e=>editMenu({target:Number(e.target.value)})}/></Field></div><Field label="Store within this site (optional)"><NativeSelect value={menu.store_id||''} onChange={e=>editMenu({store_id:e.target.value})}><option value="">Site-level menu</option>{context?.stores.filter(s=>s.parent_id===activeSite).map(s=><option key={s.id} value={s.id}>{s.name} ({s.code})</option>)}</NativeSelect></Field><div className="menu-generate"><Field label="Category"><NativeSelect value={menuCategory} onChange={e=>setMenuCategory(e.target.value)}><option>All categories</option>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</NativeSelect></Field><Field label="Number of dishes"><Input type="number" min="1" max="50" value={menuCount} onChange={e=>setMenuCount(Number(e.target.value))}/></Field><Button disabled={!menuCount||!menu.target||menu.target>100} onClick={()=>{const pool=data.recipes.filter(r=>r.is_active&&(menuCategory==='All categories'||r.category===menuCategory));const picked=pool.slice(0,menuCount);if(!picked.length){setError('No saved active recipes match this category.');return;}if(menu.items.length&&!window.confirm('Replace the current menu items?'))return;editMenu({items:picked.map(r=>{const c=recipeCost(r,data.inventory);return {recipe_id:r.id,price:c===null?0:Math.ceil(c/(menu.target/100)),portions:1,sold:null};})});setNotice(`Added ${picked.length} recipes. Review prices before use.`);}}>Generate menu</Button><Field label="Or add a recipe"><NativeSelect value="" onChange={e=>{const r=data.recipes.find(x=>x.id===e.target.value);if(r)addMenuRecipe(r);}}><option value="">Choose recipe</option>{data.recipes.filter(r=>!menu.items.some(i=>i.recipe_id===r.id)).map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</NativeSelect></Field></div><p className="help">Generation uses saved active recipes in library order. Costed dishes receive a suggested price based on the target. Uncosted dishes need a price.</p></section>
 <section className="panel flush"><div className="table-wrap"><Table className="menu-table"><TableHeader><TableRow><TableHead>Recipe</TableHead><TableHead>Production portions</TableHead><TableHead>Price (SAR)</TableHead><TableHead>Cost / portion</TableHead><TableHead>Food cost</TableHead><TableHead>Contribution</TableHead><TableHead>Sold</TableHead><TableHead>Classification</TableHead><TableHead></TableHead></TableRow></TableHeader><TableBody>{menuRecipes.map(({item:i,recipe:r},n)=>{const c=r?recipeCost(r,data.inventory):null,margin=c===null?null:i.price-c;let classification='Needs sales';if(salesReady){const popular=(i.sold||0)/totalSold>=.7/menu.items.length;const profitable=margin!==null&&margin>=avgMargin;classification=popular?(profitable?'Star':'Plowhorse'):(profitable?'Puzzle':'Dog');}return <TableRow key={i.recipe_id}><TableCell><strong>{r?.name||'Missing recipe'}</strong><small>{r?.recipe_code}</small></TableCell><TableCell><Input aria-label={'Portions for '+r?.name} type="number" min="1" value={i.portions} onChange={e=>editMenu({items:menu.items.map((x,j)=>j===n?{...x,portions:Number(e.target.value)}:x)})}/></TableCell><TableCell><Input aria-label={'Price for '+r?.name} type="number" min="0" step=".5" value={i.price} onChange={e=>editMenu({items:menu.items.map((x,j)=>j===n?{...x,price:Number(e.target.value)}:x)})}/></TableCell><TableCell>{money(c)}</TableCell><TableCell>{c===null||!i.price?'—':(c/i.price*100).toFixed(1)+'%'}</TableCell><TableCell>{money(margin)}</TableCell><TableCell><Input aria-label={'Units sold for '+r?.name} type="number" min="0" placeholder="—" value={i.sold??''} onChange={e=>editMenu({items:menu.items.map((x,j)=>j===n?{...x,sold:e.target.value===''?null:Number(e.target.value)}:x)})}/></TableCell><TableCell><Badge>{classification}</Badge></TableCell><TableCell><Button className="icon-button" aria-label={'Remove '+r?.name} onClick={()=>editMenu({items:menu.items.filter((_,j)=>j!==n)})}><X size={16}/></Button></TableCell></TableRow>;})}</TableBody></Table></div>{!menu.items.length&&<p className="padded">Generate a menu or choose recipes above.</p>}</section><p className="help">Classification requires costs, prices, and sales for every dish. Popularity threshold: 70% of an equal sales share. Profitability threshold: sales-weighted average contribution. Contribution excludes labour and overhead.</p>
 <section className="panel"><div className="section-bar"><h2>Menu export template</h2><label className="button">Load CSV headers<Input hidden type="file" accept=".csv" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{const [headers]=parseCSV(await f.text());if(!headers?.length||headers.length>30||headers.some(x=>!x.trim())||new Set(headers).size!==headers.length)throw Error('Use 1–30 unique, nonempty column headers.');editMenu({columns:headers.map(h=>({header:h,field:menuFields.includes(h)?h:''}))});}catch(e){setError((e as Error).message);}}}/></label></div><p className="help">Food Pro menu headers have not been supplied. Load your menu template and map its columns before using the file for an import.</p><div className="fields three">{(menu.columns||menuFields.map(s=>({header:s,field:s}))).map((c,n)=><Field label={c.header} key={n}><NativeSelect value={c.field} onChange={e=>editMenu({columns:(menu.columns||menuFields.map(s=>({header:s,field:s}))).map((x,j)=>j===n?{...x,field:e.target.value}:x)})}><option value="">Select value</option>{menuFields.map(f=><option key={f}>{f}</option>)}</NativeSelect></Field>)}</div></section></>}
 {tab==='Export center'&&<><div className="page-heading"><div><div className="eyebrow">FOOD PRO EXPORT</div><h1>Ready for the next system.</h1><p>Exact recipe headers. Valid JSON cells. Original inventory codes.</p></div><Badge>Food Pro recipe schema</Badge></div><div className="export-layout"><section className="panel"><div className="section-bar"><h2>Select recipes</h2><Button className="quiet" onClick={()=>setSelected(selected===null?[]:null)}>{selected===null?'Deselect all':'Select all'}</Button></div>{!data.recipes.length&&<p>Save at least one recipe to export.</p>}{data.recipes.map(r=><label className="export-recipe" key={r.id}><Input type="checkbox" checked={selected===null||selected.includes(r.id)} onChange={e=>{const base=selected===null?data.recipes.map(x=>x.id):selected;setSelected(e.target.checked?[...base,r.id]:base.filter(id=>id!==r.id));}}/><span><strong>{r.name}</strong><small>{r.recipe_code} · {r.servings} servings</small></span><Badge warn={r.ingredients.some(i=>!i.processing&&!mapIngredient(i,data.inventory))}>{r.ingredients.some(i=>!i.processing&&!mapIngredient(i,data.inventory))?'Unmatched items':'Mapped'}</Badge></label>)}</section><div><section className="panel"><div className="export-icon"><FileSpreadsheet size={28}/></div><h2>Recipe upload</h2><p>{chosen.length} recipes selected</p>{missing.length>0&&<div className="inline-note">{missing.length} ingredient lines have no inventory match. They export with blank codes. Add missing items to inventory, remap, and re-export before upload.</div>}<Button className="primary full" disabled={!chosen.length||busy} onClick={()=>{try{download('recipes.csv',recipesCSV(chosen,data.inventory));setNotice('recipes.csv downloaded.');}catch(e){setError((e as Error).message);}}}><Download size={17}/>Download recipes.csv</Button><Button className="full" disabled={!chosen.length||busy} onClick={()=>download('missing-ingredients-to-add-first.csv',missingCSV(chosen,data.inventory))}><Download size={17}/>Download missing ingredients</Button><p className="help">Missing-item codes are blank for assignment in your inventory system. Processing water is excluded. No Food Pro connection is made by this app.</p></section><section className="panel"><h3>Export checks</h3><div className="check-line"><Check size={17}/>Unique recipe codes</div><div className="check-line"><Check size={17}/>Numbered cooking steps</div><div className="check-line"><Check size={17}/>JSON ingredients, allergens, and sites</div><div className="check-line"><Check size={17}/>System units only</div></section></div></div><details className="panel"><summary>Preview first recipe row</summary><pre>{chosen.length?JSON.stringify(Object.fromEntries(HEADERS.map((h,n)=>[h,parseCSV(recipesCSV([chosen[0]],data.inventory))[1][n]])),null,2):'No recipes selected.'}</pre></details></>}
 {tab==='Templates'&&<><div className="page-heading"><div><div className="eyebrow">OUTPUT STRUCTURE</div><h1>Your templates, consistently filled.</h1><p>The recipe export follows your Food Pro specification.</p></div><Button onClick={()=>download('food-pro-recipe-template.csv',csv([HEADERS]))}><Download size={17}/>Recipe CSV template</Button></div><section className="panel"><h2>Recipe fields</h2><div className="table-wrap"><Table><TableHeader><TableRow><TableHead>CSV field</TableHead><TableHead>Value source</TableHead><TableHead>Format</TableHead></TableRow></TableHeader><TableBody>{HEADERS.map(h=><TableRow key={h}><TableCell className="code">{h}</TableCell><TableCell>{h==='ingredients'?'Recipe ingredients + inventory mapping':h==='sub_recipes'?'No sub-recipes in this version':h==='allergens'?'Inventory declarations + known recipe allergens':'Recipe builder'}</TableCell><TableCell>{['ingredients','allergens','site_ids','site_names','sub_recipes'].includes(h)?'JSON array':h==='is_active'?'true / false':h==='cuisine_type'?'general / philippines':h==='site_scope'?'all / specific':'Recipe value'}</TableCell></TableRow>)}</TableBody></Table></div></section><section className="panel"><h2>Menu templates</h2><p>Each menu can use its own CSV headers. Open a menu, load the template, then map each column to a menu value.</p><Button onClick={()=>switchTab('Menus')}>Open menus</Button></section></>}
 </main><footer className="app-footer">Recipe Studio <span>Inventory → Recipes → Menus → Food Pro</span></footer></div>
 <Dialog open={generator} onOpenChange={setGenerator}><DialogContent className="modal" showCloseButton={false} aria-describedby={undefined}><Button className="modal-close icon-button" aria-label="Close generator" onClick={()=>setGenerator(false)}><X size={20}/></Button><div className="eyebrow">RECIPE GENERATOR</div><DialogTitle asChild><h2 id="generate-title">A starting point for your next dish.</h2></DialogTitle><p>Choose a recipe pattern and batch size. Every field stays editable.</p><Field label="Recipe pattern"><NativeSelect value={pattern} onChange={e=>setPattern(Number(e.target.value))}>{PATTERNS.map((p,n)=><option key={p.name} value={n}>{p.name} · {p.cuisine==='philippines'?'Philippines':p.category}</option>)}</NativeSelect></Field><Field label="Batch serving count"><Input type="number" min="1" max="100000" value={batch} onChange={e=>setBatch(Number(e.target.value))}/></Field><div className="inline-note">Pattern-based generation. Review ingredient quantities, allergens, cooking methods, and finished yield before production.</div><div className="actions"><Button className="primary" disabled={!batch||batch<1||batch>100000} onClick={()=>{const r=scopeRecipe(generateRecipe(pattern,batch,data.inventory));setDraft(r);setScale(batch);setDirty(true);setGenerator(false);setTab('Recipes');setBulk('');}}>Generate recipe</Button><Button onClick={()=>{setDraft(scopeRecipe(blankRecipe()));setDirty(true);setGenerator(false);setTab('Recipes');}}>Start from scratch</Button></div></DialogContent></Dialog>
 <Dialog open={!!item} onOpenChange={open=>{if(!open&&!busy)setItem(null);}}>{item&&<DialogContent className="modal" showCloseButton={false} aria-describedby={undefined}><Button className="modal-close icon-button" aria-label="Close item editor" disabled={busy} onClick={()=>setItem(null)}><X size={20}/></Button><DialogTitle asChild><h2 id="item-title">{editItemCode?'Edit inventory item':'Add inventory item'}</h2></DialogTitle><p>Use the item code and name from your real inventory.</p><div className="fields two"><Field label="Item code"><Input disabled={!!editItemCode} value={item.item_code} onChange={e=>setItem({...item,item_code:e.target.value})}/></Field><Field label="Exact inventory name"><Input value={item.name} onChange={e=>setItem({...item,name:e.target.value})}/></Field><Field label="System unit"><NativeSelect value={item.unit} onChange={e=>setItem({...item,unit:e.target.value})}>{UNITS.map(u=><option key={u}>{u}</option>)}</NativeSelect></Field><Field label="Cost per unit (SAR)"><Input type="number" min="0" step="any" value={item.cost??''} onChange={e=>setItem({...item,cost:e.target.value===''?null:Number(e.target.value)})}/></Field><Field label="Category"><Input value={item.category} onChange={e=>setItem({...item,category:e.target.value})}/></Field><Field label="Allergens (comma separated)"><Input value={item.allergens.join(',')} onChange={e=>setItem({...item,allergens:e.target.value?list(e.target.value):[]})}/></Field></div><Button className="primary full" disabled={busy||!item.item_code.trim()||!item.name.trim()} onClick={()=>run(async()=>{const record={...item,id:'inv:'+item.item_code.trim(),item_code:item.item_code.trim(),name:item.name.trim(),allergens:item.allergens.filter(Boolean)};if(!editItemCode&&data.inventory.some(i=>i.item_code===record.item_code))throw Error('That code already exists. Edit the existing inventory item.');await request('POST',{kind:'inventory',items:[record]});await load();setItem(null);setNotice('Inventory item saved.');})}>{busy?'Saving…':'Save inventory item'}</Button>{error&&<p className="modal-error" role="alert">{error}</p>}</DialogContent>}</Dialog>
 </div>;
}


