import assert from 'node:assert/strict';
import {inventoryCSV,parseCSV,csv,parseQuantity,convert,generateRecipe,recipeCost,recipesCSV,missingCSV,HEADERS,validateRecipe} from '../lib/food.ts';
assert.deepEqual(parseQuantity('45 kg to 50 kg Rice'),{quantity:50,unit:'kg',name:'Rice'});
assert.deepEqual(parseQuantity('45 to 50 kg Rice'),{quantity:50,unit:'kg',name:'Rice'});
assert.deepEqual(parseQuantity('250 ml Lemon juice'),{quantity:250,unit:'ml',name:'Lemon juice'});
assert.equal(convert(250,'g','kg'),.25);assert.equal(convert(1,'l','kg'),null);
const source=[['item_code','name','unit','cost','allergens'],['REAL-01','Chicken, breast','kg',24,'["soy"]'],['REAL-02','Basmati rice','kg',8,'[]']];
assert.deepEqual(parseCSV(csv(source)),source.map(r=>r.map(String)));
const inventory=inventoryCSV(csv(source));assert.equal(inventory[0].name,'Chicken, breast');
assert.throws(()=>inventoryCSV('item_code,name,unit\nA,Rice,bag'));
assert.throws(()=>inventoryCSV('item_code,name,unit\nA,Rice,kg\nA,Milk,l'));
const r=generateRecipe(0,500,inventory);r.ingredients[0].item_code='REAL-01';r.ingredients[0].source='90 kg to 100 kg Chicken';
assert.deepEqual(validateRecipe(r),[]);assert.equal(recipeCost(r,inventory),null);
const rows=parseCSV(recipesCSV([r],inventory));assert.deepEqual(rows[0],HEADERS);assert.equal(rows[1].length,19);
const ingredients=JSON.parse(rows[1][8]);assert.equal(ingredients[0].ingredient_name,'Chicken, breast');assert.equal(ingredients[0].quantity,100);assert.equal(ingredients[0].source_quantity_text,'90 kg to 100 kg Chicken');assert.equal(ingredients[0].original_servings,500);assert.equal(ingredients[0].item_code,'REAL-01');assert.equal(ingredients[2].mapping_source,'unmatched');assert.equal(ingredients[2].sku,'');
assert.deepEqual(JSON.parse(rows[1][13]),['soy']);assert.deepEqual(JSON.parse(rows[1][9]),[]);assert.match(rows[1][10],/^1\./);
assert.equal(parseCSV(missingCSV([r],inventory)).length,4);
r.ingredients.push({name:'Water',quantity:2,unit:'l',item_code:'',source:'2 l water',original_servings:500,processing:true});assert.equal(JSON.parse(parseCSV(recipesCSV([r],inventory))[1][8]).length,5);
r.site_scope='specific';assert.ok(validateRecipe(r).length);r.site_ids=['1'];r.site_names=['Main kitchen'];assert.deepEqual(validateRecipe(r),[]);
assert.throws(()=>recipesCSV([r,r],inventory));
console.log('Passed: CSV round trips, exact headers, ranges, inventory mapping, allergens, prep water, site arrays, uniqueness and unit conversion.');
