import assert from 'node:assert/strict';
import {existsSync,readFileSync} from 'node:fs';
import {inventoryCSV,parseCSV,csv,parseQuantity,convert,generateRecipe,recipeCost,recipesCSV,missingCSV,HEADERS,INVENTORY_HEADERS,MENU_PLAN_HEADERS,validateRecipe} from '../lib/food.ts';
assert.deepEqual(parseQuantity('45 kg to 50 kg Rice'),{quantity:50,unit:'kg',name:'Rice'});
assert.deepEqual(parseQuantity('45 to 50 kg Rice'),{quantity:50,unit:'kg',name:'Rice'});
assert.deepEqual(parseQuantity('250 ml Lemon juice'),{quantity:250,unit:'ml',name:'Lemon juice'});
assert.equal(convert(250,'g','kg'),.25);assert.equal(convert(1,'l','kg'),null);assert.equal(convert(1,'lb','g'),453.59237);
const partialSource=[INVENTORY_HEADERS,['REAL-01','Chicken, breast','384','KBR','','12.5','KG','24','B-1','2026-10-01','2026-12-31','REF-1','',5,50,'weighted_average'],['REAL-02','Basmati rice','384','KBR','','20','EA','8','','','','','',0,100,'weighted_average']];
assert.deepEqual(parseCSV(csv(partialSource)),partialSource.map(r=>r.map(String)));
const partialInventory=inventoryCSV(csv(partialSource));assert.equal(partialInventory[0].name,'Chicken, breast');assert.equal(partialInventory[0].unit,'kg');assert.equal(partialInventory[1].unit,'ea');assert.equal(partialInventory[0].quantity,12.5);assert.equal(partialInventory[0].batch_number,'B-1');
assert.throws(()=>inventoryCSV('item_code,ingredient_name,unit,quantity\nA,Rice,crate,1'));
assert.throws(()=>inventoryCSV('item_code,ingredient_name,unit,quantity,stock_date,expiry_date\nA,Rice,kg,1,2026-12-31,2026-01-01'));
const uploaded='/Users/abutt/Library/CloudStorage/GoogleDrive-ammen1@gmail.com/My Drive/OFFICIAL/CIO PROJECTS/CATERING SOFTWARE/LOCATIONS/KBR-384/Upload Live Srv/Final/inventory-template_Raheel.csv';
if(existsSync(uploaded)){const rows=inventoryCSV(readFileSync(uploaded,'utf8'));assert.equal(rows.length,262);assert.equal(rows[0].unit,'ea');assert.equal(rows.some(row=>row.unit==='bag'),true);}
const missingRecipe=generateRecipe(0,500,partialInventory);missingRecipe.ingredients[0].item_code='REAL-01';missingRecipe.ingredients[0].source='90 kg to 100 kg Chicken';
assert.deepEqual(validateRecipe(missingRecipe),[]);assert.equal(recipeCost(missingRecipe,partialInventory),null);assert.throws(()=>recipesCSV([missingRecipe],partialInventory),/map every production ingredient/i);
const missing=parseCSV(missingCSV([missingRecipe],partialInventory));assert.deepEqual(missing[0],INVENTORY_HEADERS);assert.equal(missing.length,4);
const fullSource=[INVENTORY_HEADERS,['REAL-01','Chicken breast','384','KBR','','100','kg','24','','2026-10-01','','','','','','weighted_average'],['REAL-02','Basmati rice','384','KBR','','100','kg','8','','2026-10-01','','','','','','weighted_average'],['REAL-03','Mixed vegetables','384','KBR','','100','kg','6','','2026-10-01','','','','','','weighted_average'],['REAL-04','Olive oil','384','KBR','','100','l','12','','2026-10-01','','','','','','weighted_average'],['REAL-05','Salt','384','KBR','','100','kg','1','','2026-10-01','','','','','','weighted_average']];
const inventory=inventoryCSV(csv(fullSource));
const r=generateRecipe(0,500,inventory);assert.ok(r.ingredients.every(i=>i.processing||i.item_code));
const rows=parseCSV(recipesCSV([r],inventory));assert.deepEqual(rows[0],HEADERS);assert.equal(rows.length,r.ingredients.filter(i=>!i.processing).length+1);assert.equal(rows[1].length,30);
const row=Object.fromEntries(HEADERS.map((h,n)=>[h,rows[1][n]]));assert.equal(row.recipe_code,r.recipe_code);assert.equal(row.item_code,'REAL-01');assert.equal(row.ingredient_name,'Chicken breast');assert.equal(Number(row.line_quantity),100);assert.equal(row.line_unit,'kg');assert.match(row.instructions,/^1\./);assert.equal(row.site_scope,'global');assert.deepEqual(JSON.parse(row.allergens),[]);
r.ingredients.push({name:'Water',quantity:2,unit:'l',item_code:'',source:'2 l water',original_servings:500,processing:true});assert.equal(parseCSV(recipesCSV([r],inventory)).length,6);
r.site_scope='specific';assert.ok(validateRecipe(r).length);r.site_ids=['1'];r.site_names=['Main kitchen'];assert.deepEqual(validateRecipe(r),[]);
assert.throws(()=>recipesCSV([r,r],inventory));
assert.deepEqual(MENU_PLAN_HEADERS.slice(0,8),['site_id','site_name','plan_date','meal_type','menu_type','menu_category','status','line_number']);
console.log('Passed: FoodProLive headers, uploaded inventory template, mapped-only recipe export, missing inventory worklist, site arrays, uniqueness, and unit conversion.');
