import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {build} from 'esbuild';
import {generateRecipe} from '../lib/food.ts';
const compiled=await build({stdin:{contents:"export * from './lib/access'; export * from './lib/data-service';",resolveDir:process.cwd(),loader:'ts'},bundle:true,platform:'node',format:'esm',write:false});
const {authenticate,requireSite,contextFor,saveLocation,saveUser,adminSnapshot,readData,writeData,deleteData,assignLegacy}=await import('data:text/javascript;base64,'+Buffer.from(compiled.outputFiles[0].text).toString('base64'));
const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const file of ['0000_old_namora.sql','0001_special_gladiator.sql'])sql.exec(readFileSync('drizzle/'+file,'utf8'));
class Statement{constructor(q,params=[]){this.q=q;this.params=params;}bind(...p){return new Statement(this.q,p);}async first(){return sql.prepare(this.q).get(...this.params)||null;}async all(){return {results:sql.prepare(this.q).all(...this.params)};}async run(){return sql.prepare(this.q).run(...this.params);}}
const db={prepare:q=>new Statement(q),async batch(statements){sql.exec('BEGIN');try{const result=[];for(const s of statements)result.push(await s.run());sql.exec('COMMIT');return result;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const ownerIdentity={id:'owner-auth',email:'owner@example.com'};
await assert.rejects(()=>authenticate(db,null,'owner@example.com'),e=>e.status===401);
await assert.rejects(()=>authenticate(db,{id:'stranger',email:'stranger@example.com'},'owner@example.com'),e=>e.status===403);
const admin=await authenticate(db,ownerIdentity,'owner@example.com');assert.equal(admin.role,'admin');
const location=(id,kind,parent_id=null)=>({id,kind,parent_id,name:id,code:id.toUpperCase(),active:true});
await saveLocation(db,admin,location('area','area'));await saveLocation(db,admin,location('project','project','area'));
await saveLocation(db,admin,location('site-a','site','project'));await saveLocation(db,admin,location('site-b','site','project'));
await saveLocation(db,admin,location('store-a','store','site-a'));await saveLocation(db,admin,location('store-b','store','site-b'));
await assert.rejects(()=>saveLocation(db,admin,location('bad-store','store','project')));
const member={id:'member',name:'Kitchen user',email:'member@example.com',role:'member',active:true,site_ids:['site-a']};
await saveUser(db,admin,member);let user=await authenticate(db,{id:'member-auth',email:'MEMBER@example.com'},'owner@example.com');
assert.deepEqual((await contextFor(db,user)).sites.map(s=>s.id),['site-a']);
assert.deepEqual((await contextFor(db,user)).stores.map(s=>s.id),['store-a']);
await assert.rejects(()=>requireSite(db,user,'site-b'),e=>e.status===403);
await assert.rejects(()=>requireSite(db,user,null),e=>e.status===400);
await assert.rejects(()=>adminSnapshot(db,user),e=>e.status===403);
await assert.rejects(()=>saveLocation(db,user,location('forged','area')),e=>e.status===403);
await assert.rejects(()=>saveUser(db,user,{...member,role:'admin'}),e=>e.status===403);
await assert.rejects(()=>authenticate(db,{id:'other-auth',email:'member@example.com'},'owner@example.com'));
const siteA=await requireSite(db,admin,'site-a'),siteB=await requireSite(db,admin,'site-b');
const item={id:'inv:SKU-01',item_code:'SKU-01',name:'Ingredient at A',unit:'kg',cost:10,category:'Ingredient',allergens:[]};
await writeData(db,siteA,{kind:'inventory',items:[item]});await writeData(db,siteB,{kind:'inventory',items:[{...item,name:'Ingredient at B'}]});
assert.equal((await readData(db,siteA)).inventory[0].name,'Ingredient at A');assert.equal((await readData(db,siteB)).inventory[0].name,'Ingredient at B');
const r=generateRecipe(0,10,[]);r.ingredients[0].item_code='SKU-01';r.site_scope='all';r.site_ids=['site-b'];
await writeData(db,siteA,{kind:'recipe',record:r});const saved=(await readData(db,siteA)).recipes[0];assert.equal(saved.site_scope,'specific');assert.deepEqual(saved.site_ids,['SITE-A']);assert.equal((await readData(db,siteB)).recipes.length,0);
const menu={id:'m',code:'MENU',name:'Menu',target:30,store_id:'store-a',items:[{recipe_id:r.id,price:30,portions:1,sold:null}]};
await assert.rejects(()=>writeData(db,siteB,{kind:'menu',record:menu}));
await assert.rejects(()=>writeData(db,siteA,{kind:'menu',record:{...menu,store_id:'store-b'}}));
await writeData(db,siteA,{kind:'menu',record:menu});await assert.rejects(()=>deleteData(db,siteB,'recipe',r.id),e=>e.status===404);
await saveUser(db,admin,{...member,site_ids:['site-b']});user=await authenticate(db,{id:'member-auth',email:member.email},'owner@example.com');await assert.rejects(()=>requireSite(db,user,'site-a'));
await saveUser(db,admin,{...member,active:false});await assert.rejects(()=>authenticate(db,{id:'member-auth',email:member.email},'owner@example.com'));
await assert.rejects(()=>saveUser(db,admin,{...admin,active:false,site_ids:[]}));
await assert.rejects(()=>saveLocation(db,admin,{...location('store-a','store','site-b')}));
await saveLocation(db,admin,{...location('area','area'),active:false});assert.equal((await contextFor(db,admin)).sites.length,0);await assert.rejects(()=>requireSite(db,admin,'site-a'));
await saveLocation(db,admin,location('area','area'));
// Legacy transfer must preserve all records, be idempotent, and fail atomically on duplicate codes.
await db.prepare('INSERT INTO records (owner,id,kind,code,payload,updated) VALUES (?,?,?,?,?,?)').bind(admin.auth_user_id,'recipe:legacy','recipe','LEGACY',JSON.stringify({...r,id:'legacy',recipe_code:'LEGACY'}),'now').run();
await assignLegacy(db,admin,siteA);await assignLegacy(db,admin,siteA);assert.equal((await readData(db,siteA)).recipes.length,2);
await db.prepare('INSERT INTO records (owner,id,kind,code,payload,updated) VALUES (?,?,?,?,?,?)').bind(admin.auth_user_id,'inv:SKU-01','inventory','SKU-01',JSON.stringify(item),'now').run();
await assert.rejects(()=>assignLegacy(db,admin,siteA));assert.equal((await contextFor(db,admin)).legacy_count,1);
console.log('Passed: migrations, owner bootstrap, sign-in binding, admin permissions, site isolation, cross-site menu/store rejection, account deactivation, assignment revocation, inactive ancestry, and atomic legacy transfer.');
